version: '3'
services:
  app:
    environment:
      RANDOM_TREE:
      TREE_FROM_FILE:
      TREE_FILE_PATH:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    build: .
    ports:
      - 8080:8080
    links:
      - db:redis
    volumes:
      - tree-data:/data
  db:
    image: redis:alpine
    hostname: redis
    command: redis-server --appendonly yes --save 60 100
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  redis-data:
  tree-data:
